import { Box } from "@mui/material";
import TableDealer from "./tabledealer";
import DealerInfo from "./actions/dealerinfo";

//MetaData for Home page
export const metadata = {
  title: "Dealer",
  description: "Generated by go-gac.com",
};
export default function Dealer() {
  return (
    <Box component="main" sx={{minHeight:'100vh', p:{xs:1, md:5},}}>
      <DealerInfo/>
      <TableDealer/>
    </Box>
  )
};
