import { Box } from "@mui/material";

//MetaData for Home page
export const metadata = {
  title: "Report",
  description: "Generated by indoom.com",
};
export default function Report() {
  return (
    <Box component="main" sx={{minHeight:'100vh',}}>
      Report
    </Box>
  )
};
