import { Box } from "@mui/material";
import LabTabs from "./labtabs";

//MetaData for Home page
export const metadata = {
  title: "Warehouse",
  description: "Generated by indoom.com",
};
export default function Warehouse() {
  return (
    <Box component="main" sx={{minHeight:'100vh', width:'100%', p:{xs:1, md:5}}}>
      
      <LabTabs/>

    </Box>
  )
};
