import { Box } from "@mui/material";
import Safe from "./safe";
import LabTabs from "./pay/labtabs";
import Transfare from "./transfare";
import Deposit from "./deposit";
import Withdraw from "./withdraw";

//MetaData for Home page
export const metadata = {
  title: "Payment",
  description: "Generated by go-gac.com",
};
export default function Payment() {
  return (
    <Box component="main" sx={{minHeight:'100vh', width:'100%', p:{xs:1, md:5}, }}>
      
      <Safe/>

      <Box sx={{display:{xs:'block', sm:'flex'}, justifyContent:'space-between'}}>
        <Deposit/>
        <Withdraw/>
        <Transfare/>
      </Box>

      <LabTabs/>

    </Box>
  )
};
