import { Box, Button, Typography } from "@mui/material";
import Swipper from "./swiper";
import Services from "./services";
import Aboutus from "./aboutus";
import Booking from "./booking";
import WhatsAppIcon from '@mui/icons-material/WhatsApp';
import CallIcon from '@mui/icons-material/Call';
import Link from "next/link";
import Findcar from "./findcar";


//MetaData for Home page
export const metadata = {
  title: "Go Gac | Home",
  description: "Generated by German Auto Center",
};
export default function Homepage() {
  return (
    <Box sx={{minHeight: '100vh', mt: { xs: 4, sm: 5 }, }}>

      <Box sx={{display:{xs:'none', sm:'flex'}}}>
      <Link target="_blank" href={'tel:01001038389'}>
      <Button
        variant="contained" 
        color="primary" 
        sx={{
          position: 'fixed',
          bottom: 70, // المسافة من الأسفل
          right: 20, // المسافة من اليمين
          zIndex: 1000, // لجعل الزر فوق العناصر الأخرى
        }}
      >
        <CallIcon/>
      </Button>
      </Link>
      <Link target="_blank" href={'https://wa.me/+201001038389'}>
      <Button
        variant="contained" 
        color="success" 
        sx={{
          position: 'fixed',
          bottom: 20, // المسافة من الأسفل
          right: 20, // المسافة من اليمين
          zIndex: 1000, // لجعل الزر فوق العناصر الأخرى
        }}
      >
        <WhatsAppIcon/>
      </Button>
      </Link>
      </Box>

      <Box sx={{px:{xs:'0rem', md:'5rem', lg:'10rem', xl:'15rem'}}}>
        <Swipper/>
        <Aboutus/>
      </Box>

      <Services/>
      
      <Box sx={{px:{xs:'0rem', md:'5rem', lg:'10rem', xl:'15rem'}}}>
        <Findcar/>
        <Booking/>
      </Box>

    </Box>
  );
}
