import { Box, Typography } from "@mui/material";



//MetaData for Home page
export const metadata = {
    title: "History",
    description: "Generated by go-gac.com",
};
export default function History(){
    return(
        <Box component="main" sx={{minHeight:'100vh', width:'100%', p:{xs:1, md:5}, }}>
            <Typography align="center" variant="h4">السجل</Typography>
        </Box>
    )
}