import { Box } from "@mui/material";

//MetaData for Home page
export const metadata = {
  title: "Employee",
  description: "Generated by indoom.com",
};
export default function Employee() {
  return (
    <Box component="main" sx={{minHeight:'100vh',}}>
      Employee
    </Box>
  )
};
