import { Box } from "@mui/material";
import TableJobOrder from "./tablejoborder";
import FormJobOrder from "./formjoborder";

//MetaData for Home page
export const metadata = {
  title: "Job Order",
  description: "Generated by indoom.com",
};
export default function JobOrder() {
  return (
    <Box component="main" sx={{minHeight:'100vh', width:'100%', p:{xs:1, md:5}, }}>
      
      <TableJobOrder/>

    </Box>
  )
};
