import { Box } from "@mui/material";
import TableBooking from "./tablebooking";

//MetaData for Home page
export const metadata = {
  title: "Booking",
  description: "Generated by indoom.com",
};
export default function Booking(){
    return(
        <Box component="main" sx={{minHeight:'100vh', width:'100%', p:{xs:1, md:5}}}>
        
            <TableBooking/>

        </Box>
    )
}