import { Box } from "@mui/material";
import Grid from '@mui/material/Grid2';
import BanelOne from "./dash/banelone";
import BanelTwo from "./dash/baneltwo";
import BanelThree from "./dash/banelthree";
import BanelFour from "./dash/banelfour";


//MetaData for Home page
export const metadata = {
  title: "Dashboard",
  description: "Generated by indoom.com",
};
export default function Dashboard() {
  return (
    <Box component="main" sx={{minHeight:'100vh', width:'100%', p:{xs:1, md:3, lg:5}, }}>
      <Grid container spacing={3}>
      
        <BanelOne/>
        <BanelTwo/>
        <BanelThree/>
        <BanelFour/>
        
      </Grid>
    </Box>
  )
};
