import { Box } from "@mui/material";
import TableUser from "./tableuser";

//MetaData for Home page
export const metadata = {
  title: "Users",
  description: "Generated by indoom.com",
};
export default function Users() {
  return (
    <Box component="main" sx={{minHeight:'100vh', width:'100%', p:5}}>
      <TableUser/>
    </Box>
  )
};
